version: "3.9"

services:
  #new app (angular_app)
  angular_app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./angular/my-front-app/
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
